###/bookings/

POST http://localhost:8080/bookings/createBooking
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

{
  "user": {
    "userId": 42
  },
  "payment": {
    "paymentId":37
  },
  "passengers": [
    {
    "passengerName": "Liam",
    "passengerLastName": "Gamarra",
    "passengerContactNumber": "1234567890"
    },
    {
      "passengerName": "Liam's wife",
      "passengerLastName": "Ms. G",
      "passengerContactNumber": "1234567890"
    }
  ],
  "isRoundTrip": true
}

###

GET http://localhost:8080/bookings/56
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk


### /users/

POST http://localhost:8080/users/createUser
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

{
  "userEmail": "liam@hotmail.com",
  "userPassword": "password"
}

###

GET http://localhost:8080/users/48
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

###/payment

POST http://localhost:8080/payments/createPayment
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

{
    "paymentAmount": 99
}

###

GET http://localhost:8080/payments/36
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk


###/airports
GET http://localhost:8080/airports/getAllAirports
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

###

GET http://localhost:8080/airports/2
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

###/flights

POST http://localhost:8080/flights/createFlight
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

{
  "flightNumber": "AIRPERU2024",
    "airportDeparture": {
        "airportId": 1
    },
    "airportDestination": {
        "airportId": 2
    },
    "flightDepartureTime": "2021-04-01T12:00:00",
    "flightDestinationTime": "2021-04-01T14:00:00",
    "flightPrice": 99
}

###

GET http://localhost:8080/flights/32
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk


###

GET http://localhost:8080/flights/getAllFlights
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

###/passengers
POST http://localhost:8080/passengers/createPassenger
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

{
    "passengerName": "Liam",
    "passengerLastName": "Gamarra",
  "passengerContactNumber": "1234567890"
}

###
GET http://localhost:8080/passengers/1
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

