###/bookings/
POST http://localhost:8080/bookings/createBooking
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

{
  "user": {
    "userId": 35
  },
  "payment": {
    "paymentId":30
  },
  "isRoundTrip": true
}
###
GET http://localhost:8080/bookings/50
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk


### /users/
POST http://localhost:8080/users/createUser
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

{
  "userEmail": "liam@hotmail.com",
  "userPassword": "password"
}

###
GET http://localhost:8080/users/35
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

###/payment
POST http://localhost:8080/payments/createPayment
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

{
    "paymentAmount": 123
}

###
GET http://localhost:8080/payments/29
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk


###/airports

GET http://localhost:8080/airports/getAllAirports
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

###
GET http://localhost:8080/airports/2
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

###/flights
POST http://localhost:8080/flights/createFlight
Content-Type: application/json
Authorization: Basic dGVvOnBhc3N3b3Jk

{
    "airportDeparture": {
        "airportId": 6
    },
    "airportDestination": {
        "airportId": 5
    },
    "flightDepartureTime": "2021-04-01T12:00:00",
    "flightDestinationTime": "2021-04-01T14:00:00",
    "flightPrice": 109
}